# Generated by Django 4.2.3 on 2023-08-21 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalexam',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
