# Generated by Django 4.2.3 on 2023-08-21 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0002_physicalexam_date_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalexam',
            name='date_recorded',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
