# Generated by Django 4.0.4 on 2023-01-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0003_alter_patient_histopath_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
