# Generated by Django 4.0.4 on 2023-01-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0005_remove_screening_bonescan_remove_screening_fdgpetct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assessment',
            field=models.CharField(blank=True, choices=[('Low Risk', 'Low Risk'), ('Intermediate Risk', 'Intermediate Risk'), ('High Risk', 'High Risk')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_of_treatment',
            field=models.CharField(choices=[('Hormonal Treatment', 'Hormonal Treatment'), ('Radiation Therapy', 'Radiation Therapy'), ('Chemotherapy', 'Chemotherapy'), ('Others', 'Others')], max_length=120),
        ),
    ]
