# Generated by Django 4.2.3 on 2023-08-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0005_alter_patient_histopath_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalexam',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
