# Generated by Django 4.0.4 on 2023-01-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0006_patient_assessment_alter_patient_type_of_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fdgpetct',
            name='lesion',
        ),
        migrations.RemoveField(
            model_name='gapsma',
            name='lesion',
        ),
        migrations.AddField(
            model_name='patient',
            name='choices',
            field=models.CharField(blank=True, choices=[('GA-68', 'GA-68'), ('F-18 PSMA', 'F-18 PSMA')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_bone_lesion_status',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_bone_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_bone_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_bone_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_brain_lesion_status',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_brain_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_brain_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_brain_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_liver_lesion_status',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_liver_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_liver_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_liver_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_lung_lesion_status',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_lung_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_lung_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_lung_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_lymph_node_lesion_status',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_lymph_node_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_lymph_node_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_lymph_node_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_prostate_lesion_status',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_prostate_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_prostate_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fdgpetct_prostate_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_bone_lesion_status',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_bone_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_bone_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_bone_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_brain_lesion_status',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_brain_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_brain_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_brain_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_liver_lesion_status',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_liver_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_liver_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_liver_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_lung_lesion_status',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_lung_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_lung_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_lung_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_lymph_node_lesion_status',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_lymph_node_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_lymph_node_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_lymph_node_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_prostate_lesion_status',
            field=models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_prostate_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_prostate_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gapsma_prostate_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='Lesion',
        ),
    ]
