# Generated by Django 4.0.4 on 2023-01-19 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0007_remove_fdgpetct_lesion_remove_gapsma_lesion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecog_score', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('bmi', models.IntegerField(blank=True)),
                ('bp', models.IntegerField(blank=True)),
                ('hr', models.IntegerField(blank=True)),
                ('pain_score', models.IntegerField(blank=True)),
                ('local_symptoms', models.CharField(blank=True, max_length=300)),
                ('systemic_symptoms', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('creatinine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wbc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rbc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hematocrit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('platelet', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lactate_hydrogenase', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alkaline_phosphatase', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sgpt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sgot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bilirubins', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('salivary_gland_status', models.CharField(choices=[('Normal', 'Normal'), ('Left Obstruction', 'Left Obstruction'), ('Right Obstruction', 'Right Obstruction')], max_length=120)),
                ('salivary_gland_image', models.ImageField(blank=True, upload_to='')),
                ('bone_metastasis_status', models.CharField(blank=True, choices=[('Metastasis', 'Metastasis'), ('No Metastasis', 'No Metastasis')], max_length=120, null=True)),
                ('bone_scan_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('renal_scintigraphy', models.ImageField(blank=True, null=True, upload_to='')),
                ('gapsma', models.CharField(blank=True, choices=[('GA-68', 'GA-68'), ('F-18 PSMA', 'F-18 PSMA')], max_length=120, null=True)),
                ('gapsma_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('gapsma_prostate_lesion_status', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('gapsma_prostate_location', models.CharField(blank=True, max_length=50, null=True)),
                ('gapsma_prostate_suv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gapsma_prostate_size', models.IntegerField(blank=True, null=True)),
                ('gapsma_lymph_node_lesion_status', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('gapsma_lymph_node_location', models.CharField(blank=True, max_length=50, null=True)),
                ('gapsma_lymph_node_suv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gapsma_lymph_node_size', models.IntegerField(blank=True, null=True)),
                ('gapsma_bone_lesion_status', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('gapsma_bone_location', models.CharField(blank=True, max_length=50, null=True)),
                ('gapsma_bone_suv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gapsma_bone_size', models.IntegerField(blank=True, null=True)),
                ('gapsma_brain_lesion_status', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('gapsma_brain_location', models.CharField(blank=True, max_length=50, null=True)),
                ('gapsma_brain_suv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gapsma_brain_size', models.IntegerField(blank=True, null=True)),
                ('gapsma_lung_lesion_status', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('gapsma_lung_location', models.CharField(blank=True, max_length=50, null=True)),
                ('gapsma_lung_suv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gapsma_lung_size', models.IntegerField(blank=True, null=True)),
                ('gapsma_liver_lesion_status', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('gapsma_liver_location', models.CharField(blank=True, max_length=50, null=True)),
                ('gapsma_liver_suv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gapsma_liver_size', models.IntegerField(blank=True, null=True)),
                ('fdgpetct_img', models.ImageField(blank=True, upload_to='')),
                ('fdgpetct_prostate_lesion_status', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('fdgpetct_prostate_location', models.CharField(blank=True, max_length=50, null=True)),
                ('fdgpetct_prostate_suv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fdgpetct_prostate_size', models.IntegerField(blank=True, null=True)),
                ('fdgpetct_lymph_node_lesion_status', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('fdgpetct_lymph_node_location', models.CharField(blank=True, max_length=50, null=True)),
                ('fdgpetct_lymph_node_suv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fdgpetct_lymph_node_size', models.IntegerField(blank=True, null=True)),
                ('fdgpetct_bone_lesion_status', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('fdgpetct_bone_location', models.CharField(blank=True, max_length=50, null=True)),
                ('fdgpetct_bone_suv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fdgpetct_bone_size', models.IntegerField(blank=True, null=True)),
                ('fdgpetct_brain_lesion_status', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('fdgpetct_brain_location', models.CharField(blank=True, max_length=50, null=True)),
                ('fdgpetct_brain_suv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fdgpetct_brain_size', models.IntegerField(blank=True, null=True)),
                ('fdgpetct_lung_lesion_status', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('fdgpetct_lung_location', models.CharField(blank=True, max_length=50, null=True)),
                ('fdgpetct_lung_suv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fdgpetct_lung_size', models.IntegerField(blank=True, null=True)),
                ('fdgpetct_liver_lesion_status', models.CharField(blank=True, choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('fdgpetct_liver_location', models.CharField(blank=True, max_length=50, null=True)),
                ('fdgpetct_liver_suv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fdgpetct_liver_size', models.IntegerField(blank=True, null=True)),
                ('assessment', models.CharField(blank=True, choices=[('Low Risk', 'Low Risk'), ('Intermediate Risk', 'Intermediate Risk'), ('High Risk', 'High Risk')], max_length=120, null=True)),
                ('plan', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BoneScan',
        ),
        migrations.DeleteModel(
            name='Fdgpetct',
        ),
        migrations.DeleteModel(
            name='Gapsma',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='alkaline_phosphatase',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bilirubins',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='creatinine',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ecog_score',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_bone_lesion_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_bone_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_bone_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_bone_suv',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_brain_lesion_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_brain_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_brain_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_brain_suv',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_img',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_liver_lesion_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_liver_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_liver_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_liver_suv',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_lung_lesion_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_lung_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_lung_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_lung_suv',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_lymph_node_lesion_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_lymph_node_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_lymph_node_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_lymph_node_suv',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_prostate_lesion_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_prostate_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_prostate_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fdgpetct_prostate_suv',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_bone_lesion_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_bone_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_bone_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_bone_suv',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_brain_lesion_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_brain_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_brain_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_brain_suv',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_img',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_liver_lesion_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_liver_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_liver_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_liver_suv',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_lung_lesion_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_lung_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_lung_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_lung_suv',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_lymph_node_lesion_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_lymph_node_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_lymph_node_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_lymph_node_suv',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_prostate_lesion_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_prostate_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_prostate_size',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gapsma_prostate_suv',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hematocrit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hemoglobin',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lactate_hydrogenase',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='local_symptoms',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='metastasis_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pain_score',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='platelet',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='psa',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rbc',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rs',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='salivarygland',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sg_image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sgot',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sgpt',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='systemic_symptoms',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='wbc',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight',
        ),
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.DeleteModel(
            name='SalivaryGland',
        ),
        migrations.AddField(
            model_name='screening',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_1.patient'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='patient_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='part_1.patient'),
        ),
    ]
