# Generated by Django 4.2.3 on 2023-08-25 03:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0008_physicalexam_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalexam',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='id', unique=True),
        ),
    ]
