# Generated by Django 4.0.4 on 2023-01-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0008_physicalexam_screening_delete_bonescan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='gapsma',
            new_name='gapsma_choices',
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
