# Generated by Django 4.2.3 on 2023-08-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0009_alter_physicalexam_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalexam',
            name='slug',
        ),
    ]
