# Generated by Django 4.0.4 on 2023-01-20 03:59

from django.db import migrations
import part_1.models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0011_alter_screening_fdgpetct_bone_lesion_status_and_more'),
    ]

