# Generated by Django 4.2.3 on 2023-08-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0012_alter_screening_bone_scan_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='plan',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
