# Generated by Django 4.2.3 on 2023-08-31 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0013_alter_screening_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_patient', to='part_1.patient'),
        ),
    ]
