# Generated by Django 4.2.5 on 2025-07-16 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0014_alter_screening_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='histopath_details',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Age cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gleason_score',
            field=models.CharField(blank=True, choices=[('', '----------'), ('<6', 'Less than 6'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='bp',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='ecog_score',
            field=models.IntegerField(choices=[(0, '0 - Fully active'), (1, '1 - Restricted but ambulatory'), (2, '2 - Ambulatory but unable to work'), (3, '3 - Limited self-care'), (4, '4 - Completely disabled'), (5, '5 - Dead')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='hr',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='pain_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='creatinine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_brain_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Brain SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_brain_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Brain SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='salivary_gland_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
