# Generated by Django 4.2.5 on 2025-07-31 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0015_patient_histopath_details_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gleason_score',
            field=models.CharField(choices=[('', '----------'), ('<6', 'Less than 6'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='histopath_details',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='alkaline_phosphatase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='assessment',
            field=models.CharField(choices=[('Low Risk', 'Low Risk'), ('Intermediate Risk', 'Intermediate Risk'), ('High Risk', 'High Risk')], default='None', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screening',
            name='bilirubins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='bone_metastasis_status',
            field=models.CharField(choices=[('With Metastasis', 'With Metastasis'), ('No Metastasis', 'No Metastasis')], default='None', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screening',
            name='bone_scan_image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screening',
            name='creatinine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_bone_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bone Lesion Size (mm)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_bone_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bone SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_brain_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Brain Lesion Size (mm)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_brain_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Brain SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_liver_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Liver Lesion Size (mm)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_liver_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Liver SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_lung_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lung Lesion Size (mm)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_lung_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lung SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_lymph_node_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lymph Node Lesion Size (mm)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_lymph_node_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lymph Node SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_prostate_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prostate Lesion Size (mm)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_prostate_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prostate SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_bone_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bone Lesion Size (mm)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_bone_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bone SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_brain_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Brain Lesion Size (mm)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_brain_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Brain SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_choices',
            field=models.CharField(choices=[('GA-68', 'GA-68'), ('F-18 PSMA', 'F-18 PSMA')], default='None', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_liver_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Liver Lesion Size (mm)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_liver_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Liver SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_lung_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lung Lesion Size (mm)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_lung_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lung SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_lymph_node_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lymph Node Lesion Size (mm)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_lymph_node_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lymph Node SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_prostate_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prostate Lesion Size (mm)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='gapsma_prostate_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prostate SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='hematocrit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='hemoglobin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='lactate_hydrogenase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='plan',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screening',
            name='platelet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='psa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='rbc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='salivary_gland_image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screening',
            name='sgot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='sgpt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='screening',
            name='wbc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
