# Generated by Django 4.0.4 on 2023-01-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='choices',
            new_name='gapsma_choices',
        ),
        migrations.AddField(
            model_name='followup',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
