# Generated by Django 4.2.3 on 2023-08-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_4', '0002_alter_followup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='bone_scan_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='plan',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='renal_scintigraphy',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
