# Generated by Django 4.2.3 on 2023-09-01 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0014_alter_screening_patient'),
        ('part_4', '0003_alter_followup_bone_scan_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fu_patient', to='part_1.patient'),
        ),
    ]
