# Generated by Django 4.2.5 on 2025-07-16 13:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_4', '0004_alter_followup_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='alkaline_phosphatase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='followup',
            name='bilirubins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='followup',
            name='creatinine',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_bone_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bone Lesion Size'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_bone_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Bone SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_brain_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Brain Lesion Size'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_brain_suv',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Brain SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_liver_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Liver Lesion Size'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_liver_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Liver SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_lung_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lung Lesion Size'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_lung_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Lung SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_lymph_node_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lymph Node Lesion Size'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_lymph_node_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Lymph Node SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_prostate_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prostate Lesion Size'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_prostate_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prostate SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_bone_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bone Lesion Size'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_bone_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Bone SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_brain_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Brain Lesion Size'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_brain_suv',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Brain SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_liver_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Liver Lesion Size'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_liver_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Liver SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_lung_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lung Lesion Size'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_lung_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Lung SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_lymph_node_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lymph Node Lesion Size'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_lymph_node_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Lymph Node SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_prostate_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prostate Lesion Size'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_prostate_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prostate SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='hematocrit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='followup',
            name='hemoglobin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='followup',
            name='lactate_hydrogenase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='followup',
            name='platelet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='followup',
            name='psa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='followup',
            name='rbc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='followup',
            name='sgot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='followup',
            name='sgpt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='followup',
            name='wbc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
