# Generated by Django 4.2.3 on 2023-07-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttherapy',
            old_name='post_therapy_scan',
            new_name='post_therapy_scan_hours',
        ),
    ]
