# Generated by Django 4.2.3 on 2023-07-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0002_rename_post_therapy_scan_posttherapy_post_therapy_scan_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttherapy',
            old_name='furosemide',
            new_name='with_spect_ct',
        ),
    ]
