# Generated by Django 4.2.3 on 2023-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0004_alter_posttherapy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttherapy',
            name='dosimetry_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='lesion_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
