# Generated by Django 4.2.5 on 2025-07-31 18:32

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0008_alter_posttherapy_kidney_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttherapy',
            name='bone_lesion_details',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='kidney_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='kidney_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='lesions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Prostate', 'Prostate'), ('Lymph Nodes', 'Lymph Nodes'), ('Bones', 'Bones'), ('Lungs', 'Lungs'), ('Liver', 'Liver')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='post_therapy_scan_hours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='salivary_gland',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
