# Generated by Django 4.0.4 on 2023-02-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('part_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_psma', models.DateField()),
                ('premedications', models.CharField(blank=True, max_length=120, null=True)),
                ('medications', models.CharField(blank=True, max_length=120, null=True)),
                ('furosemide', models.BooleanField()),
                ('systolic', models.IntegerField(blank=True, null=True)),
                ('diastolic', models.IntegerField(blank=True, null=True)),
                ('hr', models.IntegerField(blank=True, null=True)),
                ('rr', models.IntegerField(blank=True, null=True)),
                ('saturation', models.IntegerField(blank=True, null=True)),
                ('date_therapy', models.DateField()),
                ('radiopharm', models.CharField(blank=True, max_length=120, null=True)),
                ('side_effects', models.CharField(choices=[('Fatigue', 'Fatigue'), ('Nausea or Vomiting', 'Nausea or Vomiting'), ('Dry Lips or Mouth', 'Dry Lips or Mouth'), ('Headache', 'Headache'), ('Bone Pain', 'Bone Pain')], max_length=120)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_1.patient')),
            ],
        ),
    ]
