# Generated by Django 4.2.3 on 2023-08-24 08:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideEffects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='therapy',
            name='side_effects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fatigue', 'Fatigue'), ('Nausea or Vomiting', 'Nausea or Vomiting'), ('Dry Lips or Mouth', 'Dry Lips or Mouth'), ('Headache', 'Headache'), ('Bone Pain', 'Bone Pain')], max_length=120),
        ),
    ]
