# Generated by Django 4.2.3 on 2023-08-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0002_sideeffects_alter_therapy_side_effects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SideEffects',
        ),
        migrations.AlterField(
            model_name='therapy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
