# Generated by Django 4.2.5 on 2025-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0004_alter_therapy_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='diastolic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='hr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='rr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='saturation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='systolic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
