# Generated by Django 4.2.5 on 2025-07-31 18:32

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0005_alter_therapy_diastolic_alter_therapy_hr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='diastolic',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapy',
            name='hr',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapy',
            name='radiopharm',
            field=models.CharField(default='None', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapy',
            name='rr',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapy',
            name='saturation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapy',
            name='side_effects',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fatigue', 'Fatigue'), ('Nausea or Vomiting', 'Nausea or Vomiting'), ('Dry Lips or Mouth', 'Dry Lips or Mouth'), ('Headache', 'Headache'), ('Bone Pain', 'Bone Pain')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='systolic',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
