# Generated by Django 4.2.5 on 2025-08-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0006_alter_therapy_diastolic_alter_therapy_hr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapy',
            name='diastolic',
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='systolic',
        ),
        migrations.AddField(
            model_name='therapy',
            name='bp',
            field=models.CharField(default='N/A', max_length=120),
        ),
    ]
