# Generated by Django 4.2.5 on 2025-08-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0007_remove_therapy_diastolic_remove_therapy_systolic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='bp',
            field=models.CharField(max_length=120),
        ),
    ]
